"""initial schema

Revision ID: 7136cc209524
Revises: 
Create Date: 2026-01-26 07:21:39.594527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7136cc209524'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_stripe_events_processed', 'stripe_events', ['processed_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_item_id', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', 'HIGH_FREQUENCY', name='tier'), nullable=False),
    sa.Column('billing_status', sa.Enum('ACTIVE', 'TRIALING', 'PAST_DUE', 'CANCELED', 'CANCELING', name='billingstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index('idx_users_clerk_id', 'users', ['clerk_id'], unique=False)
    op.create_index('idx_users_stripe_customer', 'users', ['stripe_customer_id'], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('organism_yaml', sa.Text(), nullable=False),
    sa.Column('canvas_state', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('STOPPED', 'STARTING', 'RUNNING', 'STOPPING', 'ERROR', name='flowstatus'), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flows_status', 'flows', ['status'], unique=False)
    op.create_index('idx_flows_user_id', 'flows', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workflow_runs', sa.Integer(), nullable=False),
    sa.Column('llm_tokens_in', sa.Integer(), nullable=False),
    sa.Column('llm_tokens_out', sa.Integer(), nullable=False),
    sa.Column('wasm_cpu_seconds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('storage_gb_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_runs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_user_period', 'usage_records', ['user_id', 'period_start'], unique=True)
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('key_hint', sa.String(length=20), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_api_keys_user_provider', 'user_api_keys', ['user_id', 'provider'], unique=True)
    op.create_table('triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('WEBHOOK', 'SCHEDULE', 'MANUAL', name='triggertype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('webhook_token', sa.String(length=64), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_token')
    )
    op.create_index('idx_triggers_flow_id', 'triggers', ['flow_id'], unique=False)
    op.create_index('idx_triggers_webhook_token', 'triggers', ['webhook_token'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('trigger_id', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.Enum('WEBHOOK', 'SCHEDULE', 'MANUAL', name='triggertype'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'ERROR', 'TIMEOUT', name='executionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_payload', sa.Text(), nullable=True),
    sa.Column('output_payload', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_executions_flow_id', 'executions', ['flow_id'], unique=False)
    op.create_index('idx_executions_started_at', 'executions', ['started_at'], unique=False)
    op.create_index('idx_executions_status', 'executions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_executions_status', table_name='executions')
    op.drop_index('idx_executions_started_at', table_name='executions')
    op.drop_index('idx_executions_flow_id', table_name='executions')
    op.drop_table('executions')
    op.drop_index('idx_triggers_webhook_token', table_name='triggers')
    op.drop_index('idx_triggers_flow_id', table_name='triggers')
    op.drop_table('triggers')
    op.drop_index('idx_user_api_keys_user_provider', table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index('idx_usage_user_period', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('idx_flows_user_id', table_name='flows')
    op.drop_index('idx_flows_status', table_name='flows')
    op.drop_table('flows')
    op.drop_index('idx_users_stripe_customer', table_name='users')
    op.drop_index('idx_users_clerk_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_stripe_events_processed', table_name='stripe_events')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
